### ISSUE TITLE
example xml for gbk output

### ISSUE THREAD

**Issue by eparejatobes** [bg7/BG7#11]
there's no example/template xml file of the one needed to generate gbk output

**Comment by pablopareja** [comment]
Ok, I think either Marina or Raquel can prepare a better suited sample file than me _(many times I know the name of fields but I don't actually have any clue of what that may be...)_

**Comment by rtobes** [comment]
The xmls from E. coli outbreak  with the corresponding gbk could be a good example

**Comment by pablopareja** [comment]
@rtobes (you should upload a picture or something) your avatar is your beloved 'octocat' right now ;)

**Comment by eparejatobes** [comment]
I'm using this for bg7 install: http://resources.ohnosequences.com/bg7/0.9/resources/genbankOutputConf.xml.template

If that's ok, add it to repo (resources folder or something like that)
