### ISSUE TITLE
readlink error on macosx

### ISSUE THREAD

**Issue by zachcp** [bg7/BG7#31]
Hi BG7 Team,

In trying the BG7 platform I ran into a problem with your launcher script. I am running BG7 with the example data you provide as follows, but get an error in readlines:

```
/bin/bg7 -g escherichia_coli_o104_h4_str._ty-2482_1_supercontigs.fasta -c genetic_code.txt -p EHEC_ReferenceProteins_17_08_2012.fasta -r EHEC_Reference_RNAs.frn -G GenBankExternalData.xml -v
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

A quick google search points me to a [this post](http://stackoverflow.com/questions/5756524/how-to-get-absolute-path-name-of-shell-script-on-macos) which  says that readlines -f isn't possible on MacOSX. They recommend a few alternatives, but I ended up doing a find/replace in bin/bg7 to use 'greadlines' instead of 'readlines.' 

So BG7 won't work out of the gate for your Mac users.

thanks and looking forward to testing BG7,
zach cp

**Comment by eparejatobes** [comment]
yep, OSX compat of the scripts is something that we didn't tested yet. We'll try to release a more compatible version
