### ISSUE TITLE
no /proc/cpuinfo on MAC

### ISSUE THREAD

**Issue by zachcp** [bg7/BG7#32]
As a follow up to [Issue 31](https://github.com/bg7/BG7/issues/31), there is another Mac-specific error in the launch script. 

```
./bin/bg7 -g escherichia_coli_o104_h4_str._ty-2482_1_supercontigs.fasta -c genetic_code.txt -p EHEC_ReferenceProteins_17_08_2012.fasta -r EHEC_Reference_RNAs.frn -G GenBankExternalData.xml 
grep: /proc/cpuinfo: No such file or directory
```

To get around the error I can manually set the number of cores (line217) to:
 `cores + "1"` which works fine but any higher number of cores will crash the application because, apparently, threading is not supported on  OSX .

best regards,
zach cp

**Comment by mscook** [comment]
Hi,

This is not official, but I did something like this:

https://gist.github.com/4174156

(want to be able to set the number of CPU/threads when running in a shared environment)

Cheers

Mitch

**Comment by mscook** [comment]
Please note:

Changes on lines 55-56 relate to issue 22 (which has not been resolved).

Cheers

Mitch

**Comment by eparejatobes** [comment]
yeah we need to improve OS compatibility of the scripts
