### ISSUE TITLE
Correct package tree for new version

### ISSUE THREAD

**Issue by pablopareja** [bg7/BG7#42]
I was wondering what would be the correct new package name tree for the new version that uses sbt?

The current structure looks like this: 
`com.era7.bioinfo.annotation`
Perhaps we should change it to:
`com.ohnosequences.bg7`

What do you think?

**Comment by eparejatobes** [comment]
yes, `com.ohnosequences.bg7`

**Comment by pablopareja** [comment]
OK :+1:

**Comment by pablopareja** [comment]
Closing this... 

:octopus:
