### ISSUE TITLE
Is this code still supported?

### ISSUE THREAD

**Issue by splaisan** [bg7/BG7#48]
I tried to install but did not find any info about it nor on how to use the tutorial data.
Is BG7 one of these orphan projects that dies after publication or is it functional?
Any help welcome!

**Comment by splaisan** [comment]
I tried the following:

* chmod +x bin/bg7
* unzip the test data
* created folder for results 'bg7_example'
* launched the bg7 command in BG7 folder using all inputs from the test archive:

> bin/bg7 -n bg7_example \
> -g bg7_example_input_files/escherichia_coli_o104_h4_str._ty-2482_1_supercontigs.fasta \
> -p bg7_example_input_files/EHEC_ReferenceProteins_17_08_2012.fasta \
> -r bg7_example_input_files/EHEC_Reference_RNAs.frn \
> -c bg7_example_input_files/genetic_code.txt \
> -o bg7_example \
> -G bg7_example_input_files/GenBankExternalData.xml

* I got this as a result:

```
logging your params to /opt/biotools/BG7/bg7_example/params.log
it looks like this machine has 88 cores, will use that for blast settings
creating RNAs blast db
RNA blast db created: /opt/biotools/BG7/bg7_example/bg7_example.rnas.db
if you want, you can check makeblastdb log: /opt/biotools/BG7/bg7_example/bg7_example.rnas.db.log
running blastn: RNAs vs genome sequence
done! will do a basic results check now
checking if blast xml output file looks ok...
```

* the result folder has:

```
$ ll bg7_example/
total 128K
drwxr-xr-x 2 u0002316 domain users 4.0K Aug 14 11:30 .
drwxr-xr-x 9 u0002316 domain users 4.0K Aug 14 11:29 ..
-rw-r--r-- 1 u0002316 domain users  69K Aug 14 11:30 bg7_example_RNA_blastn.xml
-rw-r--r-- 1 u0002316 domain users  361 Aug 14 11:30 bg7_example.rnas.db.log
-rw-r--r-- 1 u0002316 domain users  22K Aug 14 11:30 bg7_example.rnas.db.nhr
-rw-r--r-- 1 u0002316 domain users 2.0K Aug 14 11:30 bg7_example.rnas.db.nin
-rw-r--r-- 1 u0002316 domain users  12K Aug 14 11:30 bg7_example.rnas.db.nsq
-rw-r--r-- 1 u0002316 domain users  529 Aug 14 11:30 params.log
```

this does not look like completed to me ...

**Comment by tseemann** [comment]
You can always try Prokka https://github.com/tseemann/prokka :-)

**Comment by splaisan** [comment]
Thanks @tseemann; I was hoping this one was still active, looked nice and was published ...... one more to the sink!

**Comment by tseemann** [comment]
BG7 is good in that it aligns known proteins to the genome, so you are more likely to get the correct start codon. Prokka 1.x predicts genes *ab initio* and sometimes gets it wrong.  Prokka 2.x will likely incorporate both ideas.
